/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as FingerprintsRouteImport } from './routes/fingerprints'
import { Route as KernelsRouteImport } from './routes/kernels'
import { Route as ProxiesRouteImport } from './routes/proxies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EnvironmentsIndexRouteImport } from './routes/environments.index'
import { Route as EnvironmentsNewRouteImport } from './routes/environments.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as EnvironmentsEnvironmentIdEditRouteImport } from './routes/environments.$environmentId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintsRoute = FingerprintsRouteImport.update({
  id: '/fingerprints',
  path: '/fingerprints',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelsRoute = KernelsRouteImport.update({
  id: '/kernels',
  path: '/kernels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxiesRoute = ProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsIndexRoute = EnvironmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnvironmentsRoute,
} as any)
const EnvironmentsNewRoute = EnvironmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EnvironmentsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const EnvironmentsEnvironmentIdEditRoute =
  EnvironmentsEnvironmentIdEditRouteImport.update({
    id: '/$environmentId/edit',
    path: '/$environmentId/edit',
    getParentRoute: () => EnvironmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/environments': typeof EnvironmentsRouteWithChildren
  '/fingerprints': typeof FingerprintsRoute
  '/kernels': typeof KernelsRoute
  '/proxies': typeof ProxiesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/environments/new': typeof EnvironmentsNewRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/environments/': typeof EnvironmentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/environments/$environmentId/edit': typeof EnvironmentsEnvironmentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/fingerprints': typeof FingerprintsRoute
  '/kernels': typeof KernelsRoute
  '/proxies': typeof ProxiesRoute
  '/environments/new': typeof EnvironmentsNewRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/environments': typeof EnvironmentsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/environments/$environmentId/edit': typeof EnvironmentsEnvironmentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/environments': typeof EnvironmentsRouteWithChildren
  '/fingerprints': typeof FingerprintsRoute
  '/kernels': typeof KernelsRoute
  '/proxies': typeof ProxiesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/environments/new': typeof EnvironmentsNewRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/environments/': typeof EnvironmentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/environments/$environmentId/edit': typeof EnvironmentsEnvironmentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/environments'
    | '/fingerprints'
    | '/kernels'
    | '/proxies'
    | '/settings'
    | '/environments/new'
    | '/settings/storage'
    | '/environments/'
    | '/settings/'
    | '/environments/$environmentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/fingerprints'
    | '/kernels'
    | '/proxies'
    | '/environments/new'
    | '/settings/storage'
    | '/environments'
    | '/settings'
    | '/environments/$environmentId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/environments'
    | '/fingerprints'
    | '/kernels'
    | '/proxies'
    | '/settings'
    | '/environments/new'
    | '/settings/storage'
    | '/environments/'
    | '/settings/'
    | '/environments/$environmentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  EnvironmentsRoute: typeof EnvironmentsRouteWithChildren
  FingerprintsRoute: typeof FingerprintsRoute
  KernelsRoute: typeof KernelsRoute
  ProxiesRoute: typeof ProxiesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprints': {
      id: '/fingerprints'
      path: '/fingerprints'
      fullPath: '/fingerprints'
      preLoaderRoute: typeof FingerprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernels': {
      id: '/kernels'
      path: '/kernels'
      fullPath: '/kernels'
      preLoaderRoute: typeof KernelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxies': {
      id: '/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof ProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/': {
      id: '/environments/'
      path: '/'
      fullPath: '/environments/'
      preLoaderRoute: typeof EnvironmentsIndexRouteImport
      parentRoute: typeof EnvironmentsRoute
    }
    '/environments/new': {
      id: '/environments/new'
      path: '/new'
      fullPath: '/environments/new'
      preLoaderRoute: typeof EnvironmentsNewRouteImport
      parentRoute: typeof EnvironmentsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/environments/$environmentId/edit': {
      id: '/environments/$environmentId/edit'
      path: '/$environmentId/edit'
      fullPath: '/environments/$environmentId/edit'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdEditRouteImport
      parentRoute: typeof EnvironmentsRoute
    }
  }
}

interface EnvironmentsRouteChildren {
  EnvironmentsNewRoute: typeof EnvironmentsNewRoute
  EnvironmentsIndexRoute: typeof EnvironmentsIndexRoute
  EnvironmentsEnvironmentIdEditRoute: typeof EnvironmentsEnvironmentIdEditRoute
}

const EnvironmentsRouteChildren: EnvironmentsRouteChildren = {
  EnvironmentsNewRoute: EnvironmentsNewRoute,
  EnvironmentsIndexRoute: EnvironmentsIndexRoute,
  EnvironmentsEnvironmentIdEditRoute: EnvironmentsEnvironmentIdEditRoute,
}

const EnvironmentsRouteWithChildren = EnvironmentsRoute._addFileChildren(
  EnvironmentsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  EnvironmentsRoute: EnvironmentsRouteWithChildren,
  FingerprintsRoute: FingerprintsRoute,
  KernelsRoute: KernelsRoute,
  ProxiesRoute: ProxiesRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
