/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as FingerprintsRouteImport } from './routes/fingerprints'
import { Route as KernelsRouteImport } from './routes/kernels'
import { Route as ProxiesRouteImport } from './routes/proxies'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintsRoute = FingerprintsRouteImport.update({
  id: '/fingerprints',
  path: '/fingerprints',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelsRoute = KernelsRouteImport.update({
  id: '/kernels',
  path: '/kernels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxiesRoute = ProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/environments': typeof EnvironmentsRoute
  '/fingerprints': typeof FingerprintsRoute
  '/kernels': typeof KernelsRoute
  '/proxies': typeof ProxiesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/environments': typeof EnvironmentsRoute
  '/fingerprints': typeof FingerprintsRoute
  '/kernels': typeof KernelsRoute
  '/proxies': typeof ProxiesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/environments': typeof EnvironmentsRoute
  '/fingerprints': typeof FingerprintsRoute
  '/kernels': typeof KernelsRoute
  '/proxies': typeof ProxiesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/environments'
    | '/fingerprints'
    | '/kernels'
    | '/proxies'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/environments'
    | '/fingerprints'
    | '/kernels'
    | '/proxies'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/environments'
    | '/fingerprints'
    | '/kernels'
    | '/proxies'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  FingerprintsRoute: typeof FingerprintsRoute
  KernelsRoute: typeof KernelsRoute
  ProxiesRoute: typeof ProxiesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprints': {
      id: '/fingerprints'
      path: '/fingerprints'
      fullPath: '/fingerprints'
      preLoaderRoute: typeof FingerprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernels': {
      id: '/kernels'
      path: '/kernels'
      fullPath: '/kernels'
      preLoaderRoute: typeof KernelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxies': {
      id: '/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof ProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  FingerprintsRoute: FingerprintsRoute,
  KernelsRoute: KernelsRoute,
  ProxiesRoute: ProxiesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
